name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-cd:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
    # Setup
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Quality checks
    - name: Run ESLint
      run: npm run lint

    - name: Run security audit
      run: npm audit --audit-level moderate

    - name: Run unit tests with coverage
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

    # Deploy to production (commented out - requires Serverless Dashboard setup)
    # - name: Deploy to Production
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: |
    #     echo "🚀 Deploying to production environment..."
    #     serverless deploy --stage prod --verbose
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: eu-west-2

    - name: ✅ Pipeline completed
      run: echo "Pipeline completed successfully! 🎉"